name: hps
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  get_storage: ^2.1.1
  get: ^4.7.2

  # Icons
  iconsax: ^0.0.8

  # Utility Packages
  intl: ^0.20.2
  logger: ^2.5.0
  http: any
  url_launcher: ^6.3.1
  image: ^4.5.3
  shimmer: ^3.0.0
  fluttertoast: ^8.2.12
  path_provider: any

  # Page Indicator
  smooth_page_indicator: ^1.2.1

  # Share
  share_plus: ^10.1.4

  # Read More
  readmore: ^3.0.0

  # Expandable Floating Button
  flutter_speed_dial: ^7.0.0

  # Swipeable Button animation
  page_transition: ^2.2.1

  # Text
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.3
  font_awesome_flutter: ^10.8.0
  stroke_text: any

  # Firebase
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1

  # Google Maps
  google_geocoding_api: ^1.4.1
  google_maps_flutter: ^2.10.1
  custom_info_window: ^1.0.1
  image_picker: ^1.1.2
  location: ^8.0.0
  widget_to_marker: ^1.0.6
  comment_box: ^0.0.18
  geocoding: ^3.0.0
  path: any
  uuid: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/authentication/
    - assets/images/gif/
    - assets/images/profile/
    - assets/images/background/
    - assets/map_style/
    - assets/icons/



  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500